key: debag
experiment_name: debag

# -------datasets (Planetoid)-------
Planetoid: &Planetoid
 task: Transductive
 split: public
 num_train_per_class: 20
 num_val: 500
 num_test : 1000
 transform: None
 pre_transform: None
 run: 100

Cora: &Cora
  <<: *Planetoid
  dataset: Cora
  transform: T.NormalizeFeatures()
  n_feat: 1433
  n_class: 7

Citeseer: &Citeseer
  <<: *Planetoid
  dataset: CiteSeer
  transform: T.NormalizeFeatures()
  n_feat: 3703
  n_class: 6

PubMed: &PubMed
  <<: *Planetoid
  dataset: PubMed
  transform: None
  n_feat: 500
  n_class: 3

# -------datasets (Coauthor)-------
Coauthor: &Coauthor
 task: transductive
 transform: None
 pre_transform: None
 run: 10 

CS: &CS
 <<: *Coauthor
 task: Transductive
 dataset: CS
 transform: None
 n_feat: 6805
 n_class: 15
 run: 10

Physics: &Physics
 <<: *Coauthor
 task: Transductive
 dataset: Physics
 transform: None
 n_feat: 8415
 n_class: 5
 run: 10

# -------datasets (other)-------

Flickr: &Flickr
 task: Transductive
 dataset: Flickr
 transform: None
 n_feat: 500
 n_class: 7
 run: 10

PPI: &PPI
  task: Inductive
  dataset: PPI
  transform: None
  n_feat: 50
  n_class: 121
  train_graph: 20
  test_graph: 2
  run: 10


# -------model instance-------

GAT: &GAT
  n_head: 8
  n_head_last: 1
  n_layer_dropout: 0.6
  dropout: 0.6
  learing_late: 0.005
  weight_decay: 0.0005
  seed: 42
  epochs: 10000
  patience: 100
  model: GAT
  num_layer: 2
  class_num: Single
  att_type: DP
  norm: None 
  oracle_attention: False
  label_feat: False
  delta: 0.2

# -------model instance + dataset-------
GAT_cora: &GAT_cora
  <<: [*Cora,*GAT]
  n_hid: 8
  path: cora_checkpoint.pt

GAT_citeseer: &GAT_citeseer
  <<: [*Citeseer,*GAT]
  n_hid: 8
  path: citeseer_checkpoint.pt
  
GAT_PubMed: &GAT_PubMed
  <<: [*PubMed,*GAT]
  learing_late: 0.001
  n_head_last: 8
  n_hid: 8
  path: pubmed_checkpoint.pt

GAT_cs: &GAT_cs
  <<: [*CS,*GAT]
  n_hid: 16
  path: CS_checkpoint.pt

GAT_physics: &GAT_physics
  <<: [*Physics,*GAT]
  n_hid: 16
  path: Physics_checkpoint.pt

GAT_Flickr: &GAT_Flickr
  <<: [*Flickr,*GAT] 
  learing_late: 0.01 
  n_hid: 8
  norm: None
  path: flickr_checkpoint.pt

GAT_ppi: &GAT_ppi
  <<: [*PPI,*GAT]
  n_head: 4
  n_head_last: 6
  n_hid: 256
  class_num: Multi
  path: ppi_checkpoint.pt

# -------model instance (exist study)-------
GAT_cs_tuned_DP: &GAT_cs_tuned_DP
 <<: [*CS,*GAT]
 att_type: DP
 dropout: 0.8
 learing_late:  0.005
 model: GAT
 n_hid: 8
 norm: LayerNorm
 weight_decay: 0.001
 path: cs_checkpoint.pt

GAT_cs_tuned_SD: &GAT_cs_tuned_SD
 <<: [*CS,*GAT]
 att_type: SD
 dropout: 0.8
 learing_late:  0.005
 model: GAT
 n_hid: 8
 norm: LayerNorm
 weight_decay: 0.0005
 path: cs_checkpoint.pt

GAT_physics_tuned_DP: &GAT_physics_tuned_DP
 <<: [*Physics,*GAT]
 att_type: DP
 dropout: 0.8
 learing_late: 0.005
 model: GAT
 n_hid: 8
 norm: LayerNorm
 weight_decay: 0.001
 path: physics_checkpoint.pt

GAT_physics_tuned_SD: &GAT_physics_tuned_SD
 <<: [*Physics,*GAT]
 att_type: SD
 dropout: 0.6
 learing_late: 0.05
 model: GAT
 n_hid: 8
 norm: LayerNorm
 weight_decay: 0.001
 path: physics_checkpoint.pt


GAT_Flickr_tuned_DP: &GAT_Flickr_tuned_DP
  <<: [*Flickr,*GAT]
  att_type: DP
  dropout: 0.0
  learing_late:  0.01
  model: GAT 
  n_hid: 8
  norm: BatchNorm1d
  weight_decay: 0.001
  path: flickr_checkpoint.pt

GAT_Flickr_tuned_SD: &GAT_Flickr_tuned_SD
  <<: [*Flickr,*GAT]
  att_type: SD
  dropout: 0.0
  learing_late: 0.005
  model: GAT 
  n_hid: 8
  norm: BatchNorm1d
  weight_decay: 0.001
  path: flickr_checkpoint.pt

GAT_ppi_tuned_DP: &GAT_ppi_tuned_DP
 <<: [*PPI,*GAT]
 n_head: 4
 n_head_last: 6
 att_type: DP
 dropout: 0.2
 learing_late: 0.001
 model: GAT
 n_hid: 128
 norm: LayerNorm
 weight_decay: 0.001
 class_num: Multi
 path: ppi_checkpoint.pt

GAT_ppi_tuned_SD: &GAT_ppi_tuned_SD
 <<: [*PPI,*GAT]
 n_head: 4
 n_head_last: 6
 att_type: SD
 dropout: 0.8
 learing_late: 0.001 
 model: GAT
 n_hid: 128
 norm: BatchNorm1d
 weight_decay: 0
 class_num: Multi
 path: ppi_checkpoint.pt

# -------model instance (our study)-------
# DeepGAT updated Tuned hyper parameters

#cs
DeepGAT_cs_tuned_YDP_supervised_updated: &DeepGAT_cs_tuned_YDP_supervised_updated
 <<: [*CS,*GAT]
 att_type: YDP
 dropout: 0.8
 learing_late: 0.05
 model: DeepGAT
 n_hid: 15
 norm: LayerNorm
 weight_decay: 0.0001
 path: cs_checkpoint.pt

DeepGAT_cs_tuned_YSD_supervised_updated: &DeepGAT_cs_tuned_YSD_supervised_updated
 <<: [*CS,*GAT]
 att_type: YSD
 dropout: 0.8
 learing_late: 0.05
 model: DeepGAT
 n_hid: 15
 norm: LayerNorm
 weight_decay: 0.0005
 path: cs_checkpoint.pt


#physics
DeepGAT_physics_tuned_YDP_supervised_updated: &DeepGAT_physics_tuned_YDP_supervised_updated
 <<: [*Physics,*GAT]
 att_type: YDP
 dropout: 0.8
 learing_late: 0.05
 model: DeepGAT
 n_hid: 5
 norm:  LayerNorm
 weight_decay: 0
 path: physics_checkpoint.pt

DeepGAT_physics_tuned_YSD_supervised_updated: &DeepGAT_physics_tuned_YSD_supervised_updated
 <<: [*Physics,*GAT]
 att_type: YSD
 dropout:  0.6
 learing_late: 0.001
 model: DeepGAT
 n_hid: 5
 norm: None
 weight_decay:  0
 path: physics_checkpoint.pt

#Flickr
DeepGAT_Flickr_tuned_YDP_supervised_updated: &DeepGAT_Flickr_tuned_YDP_supervised_updated
 <<: [*Flickr,*GAT]
 att_type: YDP
 dropout: 0.0
 learing_late: 0.01
 model: DeepGAT
 n_hid: 7
 norm: BatchNorm1d
 weight_decay: 0
 path: flickr_checkpoint.pt
  
DeepGAT_Flickr_tuned_YSD_supervised_updated: &DeepGAT_Flickr_tuned_YSD_supervised_updated
 <<: [*Flickr,*GAT]
 att_type: YSD
 dropout: 0.0
 learing_late: 0.005
 model: DeepGAT
 n_hid: 7
 norm: BatchNorm1d
 weight_decay: 0
 path: flickr_checkpoint.pt

#ppi
DeepGAT_ppi_tuned_YDP_supervised_updated: &DeepGAT_ppi_tuned_YDP_supervised_updated
 <<: [*PPI,*GAT]
 n_head: 4
 n_head_last: 6
 att_type: YDP
 dropout: 0.8
 learing_late: 0.001  
 model: DeepGAT
 n_hid: 121
 norm: None
 weight_decay: 0
 class_num: Multi
 path: ppi_checkpoint.pt

DeepGAT_ppi_tuned_YSD_supervised_updated: &DeepGAT_ppi_tuned_YSD_supervised_updated
 <<: [*PPI,*GAT]
 n_head: 4
 n_head_last: 6
 att_type: YSD
 dropout: 0.2
 learing_late: 0.001  
 model: DeepGAT
 n_hid: 121
 norm: LayerNorm
 weight_decay: 0.001
 class_num: Multi
 path: ppi_checkpoint.pt


#debag
debag:
 <<: *GAT_cora
 model: DeepGAT
 att_type: YDP
 oracle_attention: False
 delta: 0.2
 label_feat: True
 n_hid: 64
 num_layer: 4
 epochs: 1
 run: 1


defaults:
  - override hydra/sweeper: optuna # [basic, optuna]

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    n_jobs: 1
    n_trials: 100